version: '3.5'
services:
  jenkins-agent:
    image: akhilrajmailbox/jenkins:agent
    container_name: jenkins-agent
    hostname: jenkins-agent
    restart: on-failure:5
    user: root
    ports:
      - "30022:22"
    volumes:
      - /var/lib/jenkins-slave/jenkins_agent:/var/jenkins_agent
      - /var/lib/jenkins-slave/root:/root
    networks:
      - jenkins-network

networks:
  jenkins-network:
    external: true
    name: devops-network